Feature/rgl velocity distortion v1
tier4/AWSIM pull request #168
Opened 2023-07-26 07:25 UTC by PiotrMrozik

2023-07-31 15:21 UTC, msz-rai requested changes
Good job.
Please address the comments.

2023-07-31 15:21 UTC, msz-rai commented on Assets/RGLUnityPlugin/Scripts/LidarModels/LidarConfiguration.cs
> +        /// Time offset between two consecutive firings of the whole array.
```suggestion
        /// Time offset between two consecutive firings of the whole laser array.
```

2023-07-31 15:21 UTC, msz-rai commented on Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLNativeAPI.cs
> +        public static extern int rgl_node_rays_velocity_distort(ref IntPtr node, IntPtr velocity, IntPtr angularVelocity);
Change the function signature since it changed in the native site.

2023-07-31 15:21 UTC, msz-rai commented on Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLNativeAPI.cs
> +        public static void NodeRaysVelocityDistortion(ref IntPtr node, Vector3 velocity, Vector3 angularVelocity)
```suggestion
        public static void NodeRaysVelocityDistortion(ref IntPtr node, Vector3 linearVelocity, Vector3 angularVelocity)
```
And please propagate it over the plugin.

2023-07-31 15:21 UTC, msz-rai commented on Assets/RGLUnityPlugin/Scripts/LidarSensor.cs
> +            Matrix4x4 currentTransform = gameObject.transform.localToWorldMatrix * configuration.GetLidarOriginTransfrom();
You don't need to apply `configuration.GetLidarOriginTransfrom()`. It doesn't change the speed of the sensor.

2023-07-31 15:21 UTC, msz-rai commented on Assets/RGLUnityPlugin/Scripts/LidarSensor.cs
> +            deltaRotation *= Mathf.Deg2Rad;
I'd warp it into the function and calculate it only when `applyVelocityDistortion` is true.

2023-07-31 15:21 UTC, msz-rai commented on Assets/RGLUnityPlugin/Scripts/LidarSensor.cs
> +            lastTransform = gameObject.transform.localToWorldMatrix * configuration.GetLidarOriginTransfrom();
No need to apply `configuration.GetLidarOriginTransfrom()` also.

2023-07-31 15:21 UTC, msz-rai commented on Assets/RGLUnityPlugin/Scripts/LidarSensor.cs
> +            lastTransform = gameObject.transform.localToWorldMatrix * configuration.GetLidarOriginTransfrom();
Move it at the end of this function.

2023-07-31 15:21 UTC, msz-rai commented on Assets/RGLUnityPlugin/Scripts/LidarSensor.cs
> +        private Matrix4x4 lastTransform;
It should be initialized in `Awake()` or `Start()` to avoid a jump at the start of the simulation.

2023-08-01 10:20 UTC, PiotrMrozik commented on Assets/RGLUnityPlugin/Scripts/LidarSensor.cs
> +            rglGraphLidar.SetActive(lidarVelocityDistortionNodeId, applyVelocityDistortion);
Dunno tbh. 
This one setParameter in lidarTimeOffsetsNode changes nothing, and the code is a little bit simpler here.

2023-08-07 10:03 UTC, msz-rai approved these changes
LGTM :+1:

2023-09-23 18:06 UTC, merged