Upgrade RGL to v16
tier4/AWSIM pull request #218
Opened 2023-11-10 17:22 UTC by msz-rai

2023-11-14 17:34 UTC, prybicki approved these changes

2023-11-15 07:53 UTC, mackierx111 requested changes
RGL v16 is very nice and faster! I have checked that Autoware self-driving is possible with RGL v16.

The point cloud seems to be displaying incorrectly, can you check what is causing this? I do not know if the actual point cloud output is wrong or just the visualization.

![Screenshot from 2023-11-15 02-28-11](https://github.com/tier4/AWSIM/assets/14327102/7cbd5732-8760-491d-a97c-1de66ed1ac9a)

2023-11-15 11:00 UTC, msz-rai commented
@mackierx111 
Thank you for the review :bowing_man: 
There was a bug in the visualization. I have already fixed it.
However, I have found another bug with angular Gaussian noise - its impact on point cloud increases over time when driving. I am still working on that.

2023-11-21 15:17 UTC, mackierx111 approved these changes
LGTM

2023-11-21 15:18 UTC, merged