Added IP address validation for source IP of LidarUdpPublisher
tier4/AWSIM pull request #226
Opened 2023-12-06 11:11 UTC by hosokawa-ikuto

I added an IP address validation for LidarUdpPublisher

2023-12-06 19:01 UTC, msz-rai requested changes
Good job! :+1: 
Please consider my suggestions :bowing_man:

2023-12-07 03:10 UTC, hosokawa-ikuto reviewed
IPv6 related comments were removed

2023-12-07 03:10 UTC, hosokawa-ikuto commented on Assets/RGLUnityPlugin/Scripts/LidarUdpPublisher.cs
> +                    //if (unicast.Address.AddressFamily == AddressFamily.InterNetworkV6) continue; // skip for IPv6
```suggestion
```

2023-12-07 03:10 UTC, hosokawa-ikuto commented on Assets/RGLUnityPlugin/Scripts/LidarUdpPublisher.cs
> +//using System.Net.Sockets; // for IPv6 checking
```suggestion
```

2023-12-12 08:29 UTC, mackierx111 approved these changes

2023-12-12 08:30 UTC, merged